modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/thevortex/BedrockLegendsTweaks/issues"

[[mods]]
modId="bltweaks"
version="${file.jarVersion}" 
displayName="Bedrock Legends Tweaks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrocklegends-tweaks"
logoFile="logo.png"
authors="thevortex"
description="BedrockLegends tweaks is a mod design to add specific tweaks to modpacks made by ModernGamingWorld. "

[[dependencies.bltweaks]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="apotheosis"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="appliedenergistics2"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="jei"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="jeresources" 
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="extendedcrafting"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="botania"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="refinedstorage"
    mandatory=false
    # The version range of the dependency
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="invtweaks"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="rftoolscontrol"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="rftoolsbase"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="rftoolsbuilder"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="rftoolspower"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="farmingforblockheads"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="clickmachine"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"
	
[[dependencies.bltweaks]]
    modId="cookingforblockheads"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="xnet"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="byg"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="cosmeticarmorreworked"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="creativecore"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="curios"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="demagnetize"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="enderchests"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="endermail"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="engineersdecor"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="extremesoundmuffler"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="golems"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="ironchest"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="mininggadgets"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="multibeds"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="polymorph"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="realms"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="realms"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="shetiphiancore"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="shetiphianguide"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="speedyhoppers"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="storagedrawers"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="theoneprobe"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="toolbelt"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="trashslot"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="travelersbackpack"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="usefulrailroads"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"
	
[[dependencies.bltweaks]]
    modId="valkyrielib"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="buildersaddition" 
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.bltweaks]]
    modId="betteradvancements"
    mandatory=false
    versionRange="[0,99)"
    ordering="BEFORE"
    side="BOTH"
	
# Here's another dependency
[[dependencies.bltweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17]"
    ordering="NONE"
    side="BOTH"